package space.models.api.character

data class PlanetResponseItem(
    val alternativeName: String,
    val aphelion: Int,
    val argPeriapsis: Double,
    val aroundPlanet: Any,
    val avgTemp: Int,
    val axialTilt: Double,
    val bodyType: String,
    val density: Double,
    val dimension: String,
    val discoveredBy: String,
    val discoveryDate: String,
    val eccentricity: Double,
    val englishName: String,
    val equaRadius: Double,
    val escape: Int,
    val flattening: Double,
    val gravity: Double,
    val id: String,
    val image: String,
    val inclination: Int,
    val isPlanet: Boolean,
    val longAscNode: Double,
    val mainAnomaly: Double,
    val mass: Mass,
    val meanRadius: Double,
    val moons: List<Moon>,
    val name: String,
    val perihelion: Int,
    val polarRadius: Double,
    val rel: String,
    val semimajorAxis: Int,
    val sideralOrbit: Double,
    val sideralRotation: Double,
    val vol: Vol
)